on:
  schedule:
    # Run every 5 minutes
    - cron:  '*/5 * * * *'
name: Health Check
jobs:
  health-check:
    name: Run a pvpq.net health check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            health-check/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
        working-directory: health-check 
      - run: cargo run --release -- --chat-id '${{ secrets.CHAT_ID }}' --token '${{ secrets.TOKEN }}'
        working-directory: health-check
