name: Release
"on": [push, pull_request]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Publish Image to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: sammers/wow-pla
          username: sammers
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: Deploy app to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.SSH_HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull sammers/wow-pla:latest
            docker stop wow-pla
            docker rm -f wow-pla
            docker run -e DB_PWD="${{ secrets.DB_PWD }}" --name wow-pla -d -p9000:9000 sammers/wow-pla:latest